app/app/web/strategy/__init__.py
from . import views

app/app/web/strategy/views.py
# -*- coding: utf-8 -*-
import json
import datetime
from flask import (
    Blueprint,
    redirect,
    current_app,
    render_template,
    request,
    url_for,
    flash,
    jsonify,
    session,
)
from flask_user import current_user, login_required

from app.forms import forms
from app.utils import form_utils
from app.models import StrategyModel
from app import task

blueprint = Blueprint("strategy", __name__, url_prefix="/strategy")


@blueprint.route("/_get_exchange_quote_currencies")
def _get_exchange_quote_currencies():
    exchange = request.args.get("exchange")
    quote_currencies = task.get_exchange_quote_currencies(exchange) or []
    quote_choices = []
    for q in quote_currencies:
        # value, display
        quote_choices.append((q, q.upper()))
    return jsonify(quote_choices)


@blueprint.route("/_get_available_asset_pairs")
def _get_available_asset_pairs():
    exchange = request.args.get("exchange")
    quote_currency = request.args.get("quote_currency")
    asset_pairs = task.get_exchange_asset_pairs(exchange) or []
    pair_choices = []

    # asset pairs are tuple of same pair (choice)
    for p in asset_pairs:
        quote = p.split("_")[1]
        if quote.lower() == quote_currency.lower():
            # value, display
            pair_choices.append((p, p.upper()))

    return jsonify(pair_choices)


@blueprint.route("/_get_group_indicators/")
def _get_group_indicators():
    group = request.args.get("group", "01", type=str)
    indicators = task.get_indicators_by_group(group)
    return jsonify(indicators)


@blueprint.route("/_get_indicator_params/")
def _get_indicator_params():
    indicator_abbrev = request.args.get("indicator", "01", type=str)
    params_obj = task._get_indicator_params(indicator_abbrev)
    return jsonify(params_obj)


@blueprint.route("/<strat_id>", methods=["GET"])
@login_required
def strategy_status(strat_id):
    strat = StrategyModel.query.filter_by(uuid=strat_id).first_or_404()
    if strat not in current_user.strategies:
        flash("Strategy Not Found in DB", category="error")
        current_app.logger.error(f"Strat {strat_id} not Found")

    if strat.status in ["finished", "failed"]:
        return render_template("strategy/strategy_result.html", strat=strat)

    return render_template("account/strategy_status.html", strat_id=strat_id)


@blueprint.route("backtest/strategy/<strat_id>", methods=["GET"])
def public_backtest_status(strat_id):
    return render_template("account/strategy_status.html", strat_id=strat_id)


@blueprint.route("/build", methods=["GET", "POST"])
def build_strategy():

    form = forms.BasicTradeInfoForm()
    form.asset.choices = []
    form.quote_currency.choices = []
    if form.validate_on_submit():
        live = form.trade_type.data in ["live", "paper"]
        simulate_orders = form.trade_type.data == "paper"

        strat_dict = form_utils.build_strat_dict_from_form(form)
        strat_dict["live"] = live
        strat_dict["simulate_orders"] = simulate_orders
        session["strat_dict"] = strat_dict

        job_id, queue_name = task.queue_strat(
            json.dumps(strat_dict), current_user.uuid, live, simulate_orders
        )
        return redirect(url_for("strategy.strategy_status", strat_id=job_id))

    return render_template("strategy/trading.html", form=form)


@blueprint.route("/build_advanced", methods=["GET", "POST"])
def build_strategy_advanced():
    task.indicator_group_name_selectors()
    task.all_indicator_selectors()
    form = forms.AdvancedTradeInfoForm()
    # form.base_currency.choices = []
    form.asset.choices = []
    if form.validate_on_submit():

        trading_dict = form_utils.process_trading_form(form)

        live = form.trade_type.data in ["live", "paper"]
        simulate_orders = form.trade_type.data == "paper"

        trading_dict["START"] = datetime.datetime.strftime(
            form.start.data, "%Y-%m-%d %H:%M"
        )
        trading_dict["END"] = datetime.datetime.strftime(
            form.end.data, "%Y-%m-%d %H:%M"
        )

        session["strat_dict"] = {
            "name": form.name.data,
            "trading": trading_dict,
            "live": live,
            "simulate_orders": simulate_orders,
        }

        return redirect(url_for("strategy.build_indicators"))

    return render_template("strategy/trading.html", form=form)


@blueprint.route("build/indicators", methods=["GET", "POST"])
def build_indicators():

    strat_dict = session.get("strat_dict", {})
    if not strat_dict.get("trading", {}):
        return redirect(url_for("strategy.build_strategy"))
    indicator_form = forms.IndicatorInfoForm()
    indicator_form.group.choices = task.indicator_group_name_selectors()
    indicator_form.indicator_name.choices = task.all_indicator_selectors()

    if request.method == "POST" and indicator_form.validate_on_submit():

        indicator_dict = form_utils.process_indicator_form(indicator_form)
        params = {}

        # get params outside of wtf form
        for key in request.form.keys():
            if "param-" in key:
                name, val = key.strip("param-"), request.form.get(key)
                params[name] = val

        indicator_dict["params"] = params

        strat_indicators = session["strat_dict"].get("indicators", [])
        strat_indicators.append(indicator_dict)

        session["strat_dict"]["indicators"] = strat_indicators

        # render new form if adding another
        if indicator_form.add_another.data:
            return render_template("strategy/indicators.html", form=indicator_form)

        return redirect(url_for("strategy.build_signals"))

    return render_template("strategy/indicators.html", form=indicator_form)


@blueprint.route("build/signals", methods=["GET", "POST"])
def build_signals():
    strat_dict = session.get("strat_dict", {})
    if not strat_dict.get("trading", {}):
        return redirect(url_for("strategy.build_strategy"))

    live, simulate_orders = strat_dict["live"], strat_dict["simulate_orders"]
    # get indicators from session
    # to use as param options
    # submit strat if no indicators chosen
    active_indicators = session["strat_dict"].get("indicators")
    if active_indicators is None:
        job_id, queue_name = task.queue_strat(
            json.dumps(strat_dict), current_user.uuid, live, simulate_orders
        )
        return redirect(url_for("account.strategy_status", strat_id=job_id))

    indicator_choices = [(i["name"], i["name"]) for i in active_indicators]

    signal_form = forms.SignalForm()

    signal_form.target_series.choices = indicator_choices
    signal_form.trigger_series.choices = indicator_choices

    if request.method == "POST":

        # get and setup session signal object
        existing_signals = session["strat_dict"].get("signals", {})
        existing_signals["sell"] = existing_signals.get("sell", [])
        existing_signals["buy"] = existing_signals.get("buy", [])

        signal_dict = form_utils.process_signal_form(signal_form)

        if signal_form.signal_type == "sell":
            existing_signals["sell"].append(signal_dict)
        else:
            existing_signals["buy"].append(signal_dict)

        session["strat_dict"]["signals"] = existing_signals

        # render new form if adding another
        if signal_form.add_another.data:
            return render_template("strategy/signals.html", form=signal_form)

        # remove from session if submitting strat
        strat_dict = session.pop("strat_dict")
        live, simulate_orders = strat_dict["live"], strat_dict["simulate_orders"]

        job_id, queue_name = task.queue_strat(
            json.dumps(strat_dict), current_user.uuid, live, simulate_orders
        )
        return redirect(url_for("strategy.strategy_status", strat_id=job_id))

    return render_template("strategy/signals.html", form=signal_form)

app/app/templates/strategy/indicators.html
{% extends 'flask_user/_authorized_base.html' %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
{% from "_macros.html" import render_submit_as_btn %}
{% block content %}

<h1>{%trans%}Build a Strategy{%endtrans%}</h1>

<form action="" method="POST" class="form" role="form">
    {{ form.hidden_tag() }}
    {% for field in form %}
        {% if not field.flags.hidden %}
            {% if not field.type=='SubmitField' %}
                {{ render_field(field, tabindex=loop.index*20) }}
            {% endif %}
        {% endif %}
    {% endfor %}

    <!-- Add label and group for any params that may be added -->
    <label for="param-field-group">Parameters</label>
    <div class="form-group" id="param-field-group">
    </div>

    <!-- Add submit buttons after parameters -->
    {% for field in form %}
        {% if not field.flags.hidden %}
            {% if field.type=='SubmitField' %}
                {{ render_submit_as_btn(field, tabindex=loop.index*20) }}
            {% endif %}
        {% endif %}
    {% endfor %}

</form>
{% endblock %}

{% block extra_js %}
<script charset="utf-8" type="text/javascript">

$(document).ready(function() {

    var params = $('#param-field-group')

    // jQuery selection for the 2 select boxes
    var dropdown = {
        group: $('#indicator_group_select'),
        indicator: $('#indicator_select'),

    };

    // call to update on load
    requestGroupIndicators();


    function requestGroupIndicators () {
        var send = {
            group: dropdown.group.val()
        };
        dropdown.indicator.attr('disabled', 'disabled');
        dropdown.indicator.empty();
        $.getJSON("{{ url_for('strategy._get_group_indicators') }}", send, function(data) {

            if (data) {
                updateIndicatorList(data)
            } else{
                setTimeout(function(){
                    requestGroupIndicators();
                }, 1000);
            }
        });
    }

    function requestInidicatorParams (self) {
        let indicatorAbbrev = self.options[self.selectedIndex].text
        var send = {
            indicator: indicatorAbbrev,
        };
        params.attr('disabled', 'disabled');
        params.empty();
        $.getJSON("{{ url_for('strategy._get_indicator_params') }}", send, function(data) {
            if (data) {
              console.log(data);
              addParameterFields(data)
              params.removeAttr('disabled');
            } else {
              setTimeout(function(){
                requestInidicatorParams(self);
              }, 1000);
            }
        });
    }


    // update indicator dropdown
    function updateIndicatorList (data) {
        data.forEach(function(item) {
            dropdown.indicator.append(
                $('<option>', {
                    value: item[0],
                    text: item[1]
                })
            );
        });
        dropdown.indicator.removeAttr('disabled');
    }

    function addParameterFields(new_params){
        console.log('emptying params')
        params.attr('disabled', 'disabled');
        params.empty();

        console.log('Adding ')
        console.log(new_params)

        let idx = 0
        for (var p in new_params) {

        // append to the params form group
        let label = $('<label class="control-label"></label>')
        let input = $('<input class="form-control tabindex="30" type="number">')

        label.attr('for', p)
        label.text(p)

        input.attr('id', p)
        input.attr('name', "param-" + p)
        input.text(p)
        input.val(new_params[p])

        params.append(label, input)
        }

    }

    // event listener to group dropdown change
    dropdown.group.on('change', function() {
        requestGroupIndicators();
    });

    dropdown.indicator.on('change', function() {
        // update params based on the selected indicator
        requestInidicatorParams(this);
    });
});

</script>
{% endblock %}

app/app/templates/strategy/signals.html
{% extends 'base.html' %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
{% from "_macros.html" import render_submit_as_btn %}
{% block content %}

<div class="container text-center">
    <div class="row">
       <h1 class="text-center">{%trans%}Build a Strategy{%endtrans%}</h1>
       <h3>Indicators</h3>
   </div>

</div>


<div class="container">
    <div class="row">
        <div class="col-sm-7 col-md-6 col-lg-5 col-centered">
            <form action="" method="POST" class="form" role="form">
                {{ form.hidden_tag() }}

            <div class="row">
                <div class="col-sm-4 col-centered">
                    {{render_field(form.signal_type)}}</div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-md-4">
                    {{ render_field(form.target_series) }}
                </div>
                <div class="col-sm-4 col-md-4">
                    {{ render_field(form.func) }}
                </div>
                <div id='period-field-container' class="col-sm-4 col-md-4">
                    {{ render_field(form.period) }}
                </div>
                <div id='trigger-field-container' class="col-sm-4 col-md-4">
                    {{ render_field(form.trigger_series) }}
                </div>
            </div>
            <!-- Add submit buttons after parameters -->
            {% for field in form %}
                {% if not field.flags.hidden %}
                    {% if field.type=='SubmitField' %}
                        {{ render_submit_as_btn(field, tabindex=loop.index*20) }}
                    {% endif %}
                {% endif %}
            {% endfor %}
            </form>
        </div>
    </div>
</div>



{% endblock %}
{% block extra_js %}

<script charset="utf-8" type="text/javascript">

$(document).ready(function() {

    const PERIOD_FUNCS = ['decreasing', 'increasing']
    var funcSelector = $('#signal-func-select')
    var periodField = $("#period-field-container")
    var triggerField = $('#trigger-field-container')

    // call to update on load
    upodateSignalParams();

    // function to call XHR and update indicator dropdown
    function upodateSignalParams() {

        periodField.hide();
        triggerField.hide();

        let val = funcSelector.val();
        console.log('Using param for ' + val)

        if (PERIOD_FUNCS.includes(val)) {
            periodField.show();
        }
        else {
            triggerField.show();
        }
    }

    // event listener to group dropdown change
    funcSelector.on('change', function() {
        upodateSignalParams();
    });

});

</script>
{% endblock %}

app/app/templates/strategy/strategy_result.html
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" ></script>

</head>

{% extends "base.html" %}
{% block content %}

    <h1 class="text-center">Strategy Results</h1>

    <div class="container text-center justify-left">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    Name: {{strat.name}}
                </h4>
                <h4>Status: {{strat.status}}</h4>
            <div class="card-text">
                Strategy ID: <small>{{strat.uuid}}</small> <br>
            </div>

            </div>
        </div>
    </div>

<div class="row">

    <div class=" text-center col-xs-12 col-sm-6">
        <h4>Trade Configuration</h4><hr>
            <div class="card col-centered">
              <ul class="list-group list-group-flush">
                {% for k, v in strat.trading_config.items() %}
                    <li class="list-group-item text-left">
                        {{k.title()}}: {{ v }}
                    </li>
                {% endfor %}
              </ul>
            </div>
    </div>

    <div class="text-center col-xs-12 col-sm-6">
        <h4>Result</h4><hr>
            <div class="card col-centered">
              <ul class="list-group list-group-flush">
                {% for k, v in strat.parsed_result_json.items() %}
                    <li class="list-group-item text-left col-sm-6">
                        {{k.title()}}: {{ v }}
                    </li>
                {% endfor %}
              </ul>
          </div>
    </div>

</div>
<div class="row">
    <div class="text-center col-xs-12 col-sm-6 col-centered">
        <h4>Indicators</h4><hr>
            <div class="row text-center">
             {% for i in strat.indicators_config %}
                <div class="col-xs-6 col-md-4">
                    <div class="card">
                        <h4 class="card-title">{{ i['name'] }}</h4>
                      <ul class="list-group list-group-flush text-left">
                        <li class="list-group-item">Label: {{ i['label'] }}</li>
                        <li class="list-group-item">Symbol: {{ i['symbol'] }}</li>

                        {% if i.get('params') %}
                            {% for p, v in i.get('params', {}).items() %}
                                <li class="list-group-item">{{p}}: {{v}}</li>
                            {% endfor %}
                        {% endif %}


                      </ul>
                    </div>
                </div>
            {% endfor %}
            </div>
    </div>

    <div class="text-center col-xs-12 col-sm-6 col-centered">
        <h4>Signals</h4><hr>
            <div class="row">
                <h4>Buy</h4> <hr>
                {% for i in strat.signals_config['buy'] %}
                <div class="col-xs-6 col-md-6">
                    <div class="card">
                        <h4 class="card-title">{{ i['name'] }}</h4>
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">Series: {{ i['params']['series'] }}</li>
                        <li class="list-group-item">Funtion: {{ i['func'] }}</li>
                        {% if i['params'].get('period') %}
                                <li class="list-group-item">Period: {{ i['params']['period'] }}</li>
                        {% else %}
                                <li class="list-group-item">Trigger: {{ i['params']['trigger'] }}</li>
                        {% endif %}

                      </ul>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="row">
                <h4>Sell</h4> <hr>
                {% for i in strat.signals_config['sell'] %}
                <div class="card">
                    <h4 class="card-title">{{ i['name'] }}</h4>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">Series: {{ i['params']['series'] }}</li>
                    <li class="list-group-item">Funtion: {{ i['func'] }}</li>
                    {% if i['params'].get('period') %}
                            <li class="list-group-item">Period: {{ i['params']['period'] }}</li>
                    {% else %}
                            <li class="list-group-item">Trigger: {{ i['params']['trigger'] }}</li>
                    {% endif %}

                  </ul>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>



{% endblock %}

app/app/templates/strategy/trading.html
{% extends 'flask_user/_authorized_base.html' %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
{% from "_macros.html" import render_form %}
{% block content %}

<h1 class=text-center>{%trans%}Build a Strategy{%endtrans%}</h1>
<hr>
<h3 class=text-center>Basic Configuration</h3>

{{ render_form(form) }}


{% block extra_js %}
<script charset="utf-8" type="text/javascript">

$(document).ready(function() {

    var params = $('#param-field-group')

    // jQuery selection for the 2 select boxes
    var dropdown = {
        exchange: $('#exchange_select'),
		asset: $('#asset_select'),
        quoteCurrency: $('#quote_select')
    };

	dropdown.quoteCurrency.attr('disabled', 'disabled')
	dropdown.asset.attr('disabled', 'disabled')

    // call to update on load
	requestExchangeQuoteCurrencies();
	// requestAvailableExchangePairs();



	function requestExchangeQuoteCurrencies () {
		var send = {
			exchange: dropdown.exchange.val()
		};
		dropdown.quoteCurrency.attr('disabled', 'disabled');
		dropdown.quoteCurrency.empty();
		console.log('Fetching quote currencies for ' + dropdown.exchange.val())
		var url = "{{ url_for('strategy._get_exchange_quote_currencies') }}"
		$.getJSON(url, send, function(data) {
			if (data) {
				console.log('Received quote currencies')
				updateQuoteCurrencyList(data);
				requestAvailableExchangePairs();
			} else {
				console.log('No data for quote currencies')
				setTimeout(function() {
					requestExchangeQuoteCurrencies();
				}, 1000);
			}
		});
	}

	function requestAvailableExchangePairs () {
		 var send = {
             exchange: dropdown.exchange.val(),
			 quote_currency: dropdown.quoteCurrency.val()
        };
        dropdown.asset.attr('disabled', 'disabled');
        dropdown.asset.empty();
		let url = "{{ url_for('strategy._get_available_asset_pairs') }}"
        $.getJSON(url, send, function(data) {

            if (data) {
                updateAssetList(data);
            } else{
                setTimeout(function(){

                    requestAvailableExchangePairs();
                }, 1000);
            }
        });
    }


	function updateQuoteCurrencyList (data) {

		data.forEach(function(item) {
			dropdown.quoteCurrency.append(
				$('<option>', {
					value: item[0],
					text: item[1]
				})
			);
		});
		dropdown.quoteCurrency.removeAttr('disabled');
	}

    // update asset dropdown
    function updateAssetList (data) {

        data.forEach(function(item) {
            dropdown.asset.append(
                $('<option>', {
                    value: item[0],
                    text: item[1]
                })
            );
        });
        dropdown.asset.removeAttr('disabled');
    }


    // event listener to group dropdown change
    dropdown.exchange.on('change', function() {
		requestExchangeQuoteCurrencies();
    });

    dropdown.quoteCurrency.on('change', function() {
		requestAvailableExchangePairs();

    });
});

</script>
{% endblock %}



{% endblock %}